- name: Read messages from a kafka topic from RHACM
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: "{{ HOST }}"
        port: 443
        topic: "{{ TOPIC }}"
        check_hostname: false
        cafile: "{{ CAFILE_PATH }}"
        certfile: "{{ CERTFILE_PATH }}"
        keyfile: "{{ KEYFILE_PATH }}"
        verify_mode: CERT_NONE
  rules:
     - name: Notify
       condition: event.body is defined
       action:
         debug:
    
